/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'lightlyActive' : null } |
  { 'extraActive' : null } |
  { 'veryActive' : null } |
  { 'moderatelyActive' : null } |
  { 'sedentary' : null };
export interface BaselineSnapshot {
  'metric' : string,
  'value' : string,
  'timestamp' : bigint,
  'measurementType' : { 'blood' : null } |
    { 'vitals' : null },
}
export interface BodyGoalDetails {
  'goalType' : GoalType,
  'weeklyGoalSpeed' : number,
  'targetWeight' : number,
  'currentWeight' : number,
}
export type FeedbackType = { 'offBalance' : null } |
  { 'goodJob' : null } |
  { 'notEnoughData' : null } |
  { 'overrange' : null } |
  { 'underrange' : null } |
  { 'partialFocus' : null };
export interface FoodEntry {
  'id' : bigint,
  'day' : bigint,
  'owner' : Principal,
  'calories' : number,
  'description' : string,
  'confidenceLevel' : number,
  'portionSize' : number,
  'micronutrients' : { 'fiber' : number, 'sodium' : number, 'sugar' : number },
  'macros' : { 'fat' : number, 'carbs' : number, 'protein' : number },
  'foodLabel' : string,
}
export type GoalType = { 'gainMuscle' : null } |
  { 'maintain' : null } |
  { 'gainWeight' : null } |
  { 'loseWeight' : null };
export interface HealthMetrics {
  'bmi' : number,
  'bmr' : number,
  'bmiCategory' : string,
  'tdee' : number,
}
export interface HealthTrackRecord {
  'hematocrit' : [] | [number],
  'day' : bigint,
  'glucoseFasting' : [] | [number],
  'hba1c' : [] | [number],
  'cholesterolTot' : [] | [number],
  'hemoglobin' : [] | [number],
  'systolicBP' : [] | [bigint],
  'diastolicBP' : [] | [bigint],
  'timestamp' : bigint,
  'pulse' : [] | [bigint],
  'whiteBloodCells' : [] | [number],
  'platelets' : [] | [number],
}
export interface LabVitalsMetrics {
  'hematocrit' : [] | [number],
  'glucoseFasting' : [] | [number],
  'hba1c' : [] | [number],
  'cholesterolTot' : [] | [number],
  'hemoglobin' : [] | [number],
  'systolicBP' : [] | [bigint],
  'diastolicBP' : [] | [bigint],
  'pulse' : [] | [bigint],
  'whiteBloodCells' : [] | [number],
  'platelets' : [] | [number],
}
export interface QuestionSuggestion {
  'relatedQuestions' : Array<string>,
  'question' : string,
  'answer' : string,
  'citations' : Array<string>,
}
export type Sex = { 'female' : null } |
  { 'male' : null };
export interface UserProfile {
  'age' : [] | [bigint],
  'sex' : [] | [Sex],
  'activityLevel' : [] | [ActivityLevel],
  'heightCm' : [] | [number],
  'name' : string,
  'bodyGoal' : [] | [BodyGoalDetails],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyFeedback {
  'totalCarbs' : number,
  'feedbackType' : FeedbackType,
  'avgCalories' : number,
  'totalFat' : number,
  'entriesChecked' : bigint,
  'totalProtein' : number,
  'entriesPerDay' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFoodEntry' : ActorMethod<
    [
      bigint,
      string,
      string,
      number,
      { 'fat' : number, 'carbs' : number, 'protein' : number },
      { 'fiber' : number, 'sodium' : number, 'sugar' : number },
      number,
      number,
    ],
    bigint
  >,
  'addLabVitalsSnapshot' : ActorMethod<[LabVitalsMetrics], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerHealthMetrics' : ActorMethod<[], HealthMetrics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFoodEntriesForCaller' : ActorMethod<[bigint, bigint], Array<FoodEntry>>,
  'getFullLabVitalsHistory' : ActorMethod<[], Array<HealthTrackRecord>>,
  'getLabVitalsBaseline' : ActorMethod<[], Array<BaselineSnapshot>>,
  'getPortionAdjusterGuidance' : ActorMethod<[], string>,
  'getSuggestedQuestions' : ActorMethod<[], Array<QuestionSuggestion>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyFeedback' : ActorMethod<[], WeeklyFeedback>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBodyGoal' : ActorMethod<[BodyGoalDetails], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];