/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GoalType = IDL.Variant({
  'gainMuscle' : IDL.Null,
  'maintain' : IDL.Null,
  'gainWeight' : IDL.Null,
  'loseWeight' : IDL.Null,
});
export const BodyGoalDetails = IDL.Record({
  'goalType' : GoalType,
  'weeklyGoalSpeed' : IDL.Float64,
  'targetWeight' : IDL.Float64,
  'currentWeight' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'bodyGoal' : IDL.Opt(BodyGoalDetails),
});
export const FoodEntry = IDL.Record({
  'id' : IDL.Nat,
  'day' : IDL.Int,
  'owner' : IDL.Principal,
  'calories' : IDL.Float64,
  'description' : IDL.Text,
  'confidenceLevel' : IDL.Float64,
  'portionSize' : IDL.Float64,
  'micronutrients' : IDL.Record({
    'fiber' : IDL.Float64,
    'sodium' : IDL.Float64,
    'sugar' : IDL.Float64,
  }),
  'macros' : IDL.Record({
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'protein' : IDL.Float64,
  }),
  'foodLabel' : IDL.Text,
});
export const QuestionSuggestion = IDL.Record({
  'relatedQuestions' : IDL.Vec(IDL.Text),
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'citations' : IDL.Vec(IDL.Text),
});
export const FeedbackType = IDL.Variant({
  'offBalance' : IDL.Null,
  'goodJob' : IDL.Null,
  'notEnoughData' : IDL.Null,
  'overrange' : IDL.Null,
  'underrange' : IDL.Null,
  'partialFocus' : IDL.Null,
});
export const WeeklyFeedback = IDL.Record({
  'totalCarbs' : IDL.Float64,
  'feedbackType' : FeedbackType,
  'avgCalories' : IDL.Float64,
  'totalFat' : IDL.Float64,
  'entriesChecked' : IDL.Nat,
  'totalProtein' : IDL.Float64,
  'entriesPerDay' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFoodEntry' : IDL.Func(
      [
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Record({
          'fat' : IDL.Float64,
          'carbs' : IDL.Float64,
          'protein' : IDL.Float64,
        }),
        IDL.Record({
          'fiber' : IDL.Float64,
          'sodium' : IDL.Float64,
          'sugar' : IDL.Float64,
        }),
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFoodEntriesForCaller' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getPortionAdjusterGuidance' : IDL.Func([], [IDL.Text], ['query']),
  'getSuggestedQuestions' : IDL.Func(
      [],
      [IDL.Vec(QuestionSuggestion)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyFeedback' : IDL.Func([], [WeeklyFeedback], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBodyGoal' : IDL.Func([BodyGoalDetails], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GoalType = IDL.Variant({
    'gainMuscle' : IDL.Null,
    'maintain' : IDL.Null,
    'gainWeight' : IDL.Null,
    'loseWeight' : IDL.Null,
  });
  const BodyGoalDetails = IDL.Record({
    'goalType' : GoalType,
    'weeklyGoalSpeed' : IDL.Float64,
    'targetWeight' : IDL.Float64,
    'currentWeight' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'bodyGoal' : IDL.Opt(BodyGoalDetails),
  });
  const FoodEntry = IDL.Record({
    'id' : IDL.Nat,
    'day' : IDL.Int,
    'owner' : IDL.Principal,
    'calories' : IDL.Float64,
    'description' : IDL.Text,
    'confidenceLevel' : IDL.Float64,
    'portionSize' : IDL.Float64,
    'micronutrients' : IDL.Record({
      'fiber' : IDL.Float64,
      'sodium' : IDL.Float64,
      'sugar' : IDL.Float64,
    }),
    'macros' : IDL.Record({
      'fat' : IDL.Float64,
      'carbs' : IDL.Float64,
      'protein' : IDL.Float64,
    }),
    'foodLabel' : IDL.Text,
  });
  const QuestionSuggestion = IDL.Record({
    'relatedQuestions' : IDL.Vec(IDL.Text),
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'citations' : IDL.Vec(IDL.Text),
  });
  const FeedbackType = IDL.Variant({
    'offBalance' : IDL.Null,
    'goodJob' : IDL.Null,
    'notEnoughData' : IDL.Null,
    'overrange' : IDL.Null,
    'underrange' : IDL.Null,
    'partialFocus' : IDL.Null,
  });
  const WeeklyFeedback = IDL.Record({
    'totalCarbs' : IDL.Float64,
    'feedbackType' : FeedbackType,
    'avgCalories' : IDL.Float64,
    'totalFat' : IDL.Float64,
    'entriesChecked' : IDL.Nat,
    'totalProtein' : IDL.Float64,
    'entriesPerDay' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFoodEntry' : IDL.Func(
        [
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Record({
            'fat' : IDL.Float64,
            'carbs' : IDL.Float64,
            'protein' : IDL.Float64,
          }),
          IDL.Record({
            'fiber' : IDL.Float64,
            'sodium' : IDL.Float64,
            'sugar' : IDL.Float64,
          }),
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFoodEntriesForCaller' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getPortionAdjusterGuidance' : IDL.Func([], [IDL.Text], ['query']),
    'getSuggestedQuestions' : IDL.Func(
        [],
        [IDL.Vec(QuestionSuggestion)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyFeedback' : IDL.Func([], [WeeklyFeedback], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBodyGoal' : IDL.Func([BodyGoalDetails], [], []),
  });
};

export const init = ({ IDL }) => { return []; };