/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuestionSuggestion {
    relatedQuestions: Array<string>;
    question: string;
    answer: string;
    citations: Array<string>;
}
export interface FoodEntry {
    id: bigint;
    day: bigint;
    owner: Principal;
    calories: number;
    description: string;
    confidenceLevel: number;
    portionSize: number;
    micronutrients: {
        fiber: number;
        sodium: number;
        sugar: number;
    };
    macros: {
        fat: number;
        carbs: number;
        protein: number;
    };
    foodLabel: string;
}
export interface HealthMetrics {
    bmi: number;
    bmr: number;
    bmiCategory: string;
    tdee: number;
}
export interface BodyGoalDetails {
    goalType: GoalType;
    weeklyGoalSpeed: number;
    targetWeight: number;
    currentWeight: number;
}
export interface WeeklyFeedback {
    totalCarbs: number;
    feedbackType: FeedbackType;
    avgCalories: number;
    totalFat: number;
    entriesChecked: bigint;
    totalProtein: number;
    entriesPerDay: number;
}
export interface UserProfile {
    age?: bigint;
    sex?: Sex;
    activityLevel?: ActivityLevel;
    heightCm?: number;
    name: string;
    bodyGoal?: BodyGoalDetails;
}
export enum ActivityLevel {
    lightlyActive = "lightlyActive",
    extraActive = "extraActive",
    veryActive = "veryActive",
    moderatelyActive = "moderatelyActive",
    sedentary = "sedentary"
}
export enum FeedbackType {
    offBalance = "offBalance",
    goodJob = "goodJob",
    notEnoughData = "notEnoughData",
    overrange = "overrange",
    underrange = "underrange",
    partialFocus = "partialFocus"
}
export enum GoalType {
    gainMuscle = "gainMuscle",
    maintain = "maintain",
    gainWeight = "gainWeight",
    loseWeight = "loseWeight"
}
export enum Sex {
    female = "female",
    male = "male"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFoodEntry(day: bigint, foodLabel: string, description: string, calories: number, macros: {
        fat: number;
        carbs: number;
        protein: number;
    }, micronutrients: {
        fiber: number;
        sodium: number;
        sugar: number;
    }, portionSize: number, confidenceLevel: number): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerHealthMetrics(): Promise<HealthMetrics>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFoodEntriesForCaller(startDay: bigint, endDay: bigint): Promise<Array<FoodEntry>>;
    getPortionAdjusterGuidance(): Promise<string>;
    getSuggestedQuestions(): Promise<Array<QuestionSuggestion>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeeklyFeedback(): Promise<WeeklyFeedback>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBodyGoal(details: BodyGoalDetails): Promise<void>;
}
import type { ActivityLevel as _ActivityLevel, BodyGoalDetails as _BodyGoalDetails, FeedbackType as _FeedbackType, GoalType as _GoalType, Sex as _Sex, UserProfile as _UserProfile, UserRole as _UserRole, WeeklyFeedback as _WeeklyFeedback } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFoodEntry(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: {
        fat: number;
        carbs: number;
        protein: number;
    }, arg5: {
        fiber: number;
        sodium: number;
        sugar: number;
    }, arg6: number, arg7: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFoodEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFoodEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerHealthMetrics(): Promise<HealthMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerHealthMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerHealthMetrics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodEntriesForCaller(arg0: bigint, arg1: bigint): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntriesForCaller(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntriesForCaller(arg0, arg1);
            return result;
        }
    }
    async getPortionAdjusterGuidance(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortionAdjusterGuidance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortionAdjusterGuidance();
            return result;
        }
    }
    async getSuggestedQuestions(): Promise<Array<QuestionSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestedQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestedQuestions();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyFeedback(): Promise<WeeklyFeedback> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyFeedback();
                return from_candid_WeeklyFeedback_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyFeedback();
            return from_candid_WeeklyFeedback_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBodyGoal(arg0: BodyGoalDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBodyGoal(to_candid_BodyGoalDetails_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBodyGoal(to_candid_BodyGoalDetails_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ActivityLevel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLevel): ActivityLevel {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_BodyGoalDetails_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BodyGoalDetails): BodyGoalDetails {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_FeedbackType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackType): FeedbackType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_GoalType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalType): GoalType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Sex_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sex): Sex {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklyFeedback_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklyFeedback): WeeklyFeedback {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ActivityLevel]): ActivityLevel | null {
    return value.length === 0 ? null : from_candid_ActivityLevel_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BodyGoalDetails]): BodyGoalDetails | null {
    return value.length === 0 ? null : from_candid_BodyGoalDetails_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sex]): Sex | null {
    return value.length === 0 ? null : from_candid_Sex_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalType: _GoalType;
    weeklyGoalSpeed: number;
    targetWeight: number;
    currentWeight: number;
}): {
    goalType: GoalType;
    weeklyGoalSpeed: number;
    targetWeight: number;
    currentWeight: number;
} {
    return {
        goalType: from_candid_GoalType_n17(_uploadFile, _downloadFile, value.goalType),
        weeklyGoalSpeed: value.weeklyGoalSpeed,
        targetWeight: value.targetWeight,
        currentWeight: value.currentWeight
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCarbs: number;
    feedbackType: _FeedbackType;
    avgCalories: number;
    totalFat: number;
    entriesChecked: bigint;
    totalProtein: number;
    entriesPerDay: number;
}): {
    totalCarbs: number;
    feedbackType: FeedbackType;
    avgCalories: number;
    totalFat: number;
    entriesChecked: bigint;
    totalProtein: number;
    entriesPerDay: number;
} {
    return {
        totalCarbs: value.totalCarbs,
        feedbackType: from_candid_FeedbackType_n23(_uploadFile, _downloadFile, value.feedbackType),
        avgCalories: value.avgCalories,
        totalFat: value.totalFat,
        entriesChecked: value.entriesChecked,
        totalProtein: value.totalProtein,
        entriesPerDay: value.entriesPerDay
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: [] | [bigint];
    sex: [] | [_Sex];
    activityLevel: [] | [_ActivityLevel];
    heightCm: [] | [number];
    name: string;
    bodyGoal: [] | [_BodyGoalDetails];
}): {
    age?: bigint;
    sex?: Sex;
    activityLevel?: ActivityLevel;
    heightCm?: number;
    name: string;
    bodyGoal?: BodyGoalDetails;
} {
    return {
        age: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.age)),
        sex: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.sex)),
        activityLevel: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.activityLevel)),
        heightCm: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.heightCm)),
        name: value.name,
        bodyGoal: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.bodyGoal))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lightlyActive: null;
} | {
    extraActive: null;
} | {
    veryActive: null;
} | {
    moderatelyActive: null;
} | {
    sedentary: null;
}): ActivityLevel {
    return "lightlyActive" in value ? ActivityLevel.lightlyActive : "extraActive" in value ? ActivityLevel.extraActive : "veryActive" in value ? ActivityLevel.veryActive : "moderatelyActive" in value ? ActivityLevel.moderatelyActive : "sedentary" in value ? ActivityLevel.sedentary : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gainMuscle: null;
} | {
    maintain: null;
} | {
    gainWeight: null;
} | {
    loseWeight: null;
}): GoalType {
    return "gainMuscle" in value ? GoalType.gainMuscle : "maintain" in value ? GoalType.maintain : "gainWeight" in value ? GoalType.gainWeight : "loseWeight" in value ? GoalType.loseWeight : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offBalance: null;
} | {
    goodJob: null;
} | {
    notEnoughData: null;
} | {
    overrange: null;
} | {
    underrange: null;
} | {
    partialFocus: null;
}): FeedbackType {
    return "offBalance" in value ? FeedbackType.offBalance : "goodJob" in value ? FeedbackType.goodJob : "notEnoughData" in value ? FeedbackType.notEnoughData : "overrange" in value ? FeedbackType.overrange : "underrange" in value ? FeedbackType.underrange : "partialFocus" in value ? FeedbackType.partialFocus : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Sex {
    return "female" in value ? Sex.female : "male" in value ? Sex.male : value;
}
function to_candid_ActivityLevel_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_BodyGoalDetails_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BodyGoalDetails): _BodyGoalDetails {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_GoalType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): _GoalType {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Sex_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): _Sex {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    sex?: Sex;
    activityLevel?: ActivityLevel;
    heightCm?: number;
    name: string;
    bodyGoal?: BodyGoalDetails;
}): {
    age: [] | [bigint];
    sex: [] | [_Sex];
    activityLevel: [] | [_ActivityLevel];
    heightCm: [] | [number];
    name: string;
    bodyGoal: [] | [_BodyGoalDetails];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        sex: value.sex ? candid_some(to_candid_Sex_n27(_uploadFile, _downloadFile, value.sex)) : candid_none(),
        activityLevel: value.activityLevel ? candid_some(to_candid_ActivityLevel_n29(_uploadFile, _downloadFile, value.activityLevel)) : candid_none(),
        heightCm: value.heightCm ? candid_some(value.heightCm) : candid_none(),
        name: value.name,
        bodyGoal: value.bodyGoal ? candid_some(to_candid_BodyGoalDetails_n31(_uploadFile, _downloadFile, value.bodyGoal)) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalType: GoalType;
    weeklyGoalSpeed: number;
    targetWeight: number;
    currentWeight: number;
}): {
    goalType: _GoalType;
    weeklyGoalSpeed: number;
    targetWeight: number;
    currentWeight: number;
} {
    return {
        goalType: to_candid_GoalType_n33(_uploadFile, _downloadFile, value.goalType),
        weeklyGoalSpeed: value.weeklyGoalSpeed,
        targetWeight: value.targetWeight,
        currentWeight: value.currentWeight
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): {
    female: null;
} | {
    male: null;
} {
    return value == Sex.female ? {
        female: null
    } : value == Sex.male ? {
        male: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    lightlyActive: null;
} | {
    extraActive: null;
} | {
    veryActive: null;
} | {
    moderatelyActive: null;
} | {
    sedentary: null;
} {
    return value == ActivityLevel.lightlyActive ? {
        lightlyActive: null
    } : value == ActivityLevel.extraActive ? {
        extraActive: null
    } : value == ActivityLevel.veryActive ? {
        veryActive: null
    } : value == ActivityLevel.moderatelyActive ? {
        moderatelyActive: null
    } : value == ActivityLevel.sedentary ? {
        sedentary: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): {
    gainMuscle: null;
} | {
    maintain: null;
} | {
    gainWeight: null;
} | {
    loseWeight: null;
} {
    return value == GoalType.gainMuscle ? {
        gainMuscle: null
    } : value == GoalType.maintain ? {
        maintain: null
    } : value == GoalType.gainWeight ? {
        gainWeight: null
    } : value == GoalType.loseWeight ? {
        loseWeight: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
